export const ANONYMOUS_USAGE_LIMIT = 14;
export const FREE_USER_DAILY_LIMIT = 10;
export const SIGNED_IN_USAGE_LIMIT = 20;
export const FREE_MAX_PERCENTAGE = 0.7;
export const MIN_LEARNING_PERCENTAGE = 0.3;
export const PREMIUM_INCREMENT_PER_RESPONSE = 0.2;
export const FREE_INCREMENT_PER_RESPONSE = 0.1;
export const PREMIUM_MAX_PERCENTAGE = 0.9; 